{% set name = "graphysio" %}
{% set version = "2022.7.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d18e31fafceb61deb466fd14e191172d0020772c85b52b45f28d43c4fce29850

build:
  noarch: python
  entry_points:
    - graphysio = graphysio.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.8,<3.11
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<3.11
    - pandas =1.4
    - pathvalidate =2.5.0
    - pint =0.19.2
    - pyqt =5.15.4
    - pyqtgraph =0.12.4
    - scipy =1.8.1
    - numexpr =2.8.0
    - physiocurve =2022.6.26
    - pyarrow =8.0.0
    - pyedflib =0.1.29

test:
  imports:
    - graphysio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jaj42/GraPhysio
  summary: GUI time series visualizer for biometric data
  description: |
    GraPhysio is a graphical time series visualizer created for biometric data
    signals from ICU patient monitors. It is however not limited to this. It
    can handle low frequency and high frequency data as well as aggregating and
    synchronizing signals from different sources. GraPhysio supports basic
    mathematical operations and filters and can help selecting and exporting
    time periods. GraPhysio can read data from CSV, Parquet and EDF files and
    can write CSV, Parquet, EDF and Matlab files.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/jaj42/GraPhysio

extra:
  recipe-maintainers:
    - jaj42
